// Indian construction domain knowledge, applied deterministically.
//
// The layering this enables:
//   1. rules here decode what they can, for free and with certainty
//   2. the AI pass is asked ONLY about the residue
//   3. geometry verifies both  (see `verify.ts`)
//
// Nothing here produces a quantity.
import type { CadLabel } from '../../cad/types';
import { decodeElectrical } from './electrical';

export * from './electrical';
export * from './measure';
export * from './verify';

/** discipline inferred from a layer or block name */
export type Discipline =
  | 'architectural'
  | 'structural'
  | 'electrical'
  | 'hvac'
  | 'plumbing'
  | 'fire'
  | 'civil'
  | 'annotation'
  | 'other';

const DISCIPLINE_HINTS: { re: RegExp; discipline: Discipline; label?: string }[] = [
  // annotation first — these often also contain discipline words
  { re: /^(tixt|text|txt|anno|annotation|note|title|tblk|titleblock)/i, discipline: 'annotation', label: 'Annotation' },
  { re: /\b(dim|dims|dimension)\b/i, discipline: 'annotation', label: 'Dimensions' },
  { re: /\b(grid|axis)\b/i, discipline: 'annotation', label: 'Grid' },
  { re: /\b(hatch|patt?ern)\b/i, discipline: 'annotation', label: 'Hatching' },

  { re: /\b(wall|patition|partition|brick|masonry|plaster|gyp|gypboard|shutter)\b/i, discipline: 'architectural' },
  { re: /\b(door|window|glaz|glass|louver|louvre)\b/i, discipline: 'architectural' },
  { re: /\b(furn|furniture|chair|table|desk|sofa|workstation)\b/i, discipline: 'architectural' },
  { re: /\b(floor|flooring|tile|ceiling|false\s*ceil)\b/i, discipline: 'architectural' },
  { re: /\b(stair|step|ramp|railing|handrail)\b/i, discipline: 'architectural' },

  { re: /\b(column|beam|slab|footing|foundation|pile|pedestal|rcc|rebar|reinf)\b/i, discipline: 'structural' },
  { re: /\b(steel|ms|girder|truss|purlin|bracing)\b/i, discipline: 'structural' },

  { re: /\b(elec|electric|power|light|lighting|socket|switch|cable|conduit|earth|db|panel)\b/i, discipline: 'electrical' },

  { re: /\b(hvac|ac|air\s*cond|duct|diffuser|grille|ahu|fcu|vrf|vrv|chiller|exhaust)\b/i, discipline: 'hvac' },

  { re: /\b(plumb|water|drain|sewer|sanitary|pipe|wc|basin|toilet|stp|tank)\b/i, discipline: 'plumbing' },

  { re: /\b(fire|sprinkler|hydrant|smoke|alarm|extinguisher)\b/i, discipline: 'fire' },

  { re: /\b(road|drain|culvert|kerb|paving|landscape|site)\b/i, discipline: 'civil' },
];

export interface DomainMeaning {
  label: string;
  discipline: Discipline;
  evidence: string;
  confidence: number;
}

/**
 * Decode a raw CAD block/layer name using domain rules alone.
 * Returns null when nothing applies — the caller should then ask a model.
 */
export function decodeName(raw: string): DomainMeaning | null {
  const name = raw.trim();
  if (!name) return null;

  // anonymous DXF blocks are generated geometry, never symbols
  if (/^\*[A-Z]\d+$/i.test(name)) return null;
  // opaque autogenerated block ids — the case the AI pass exists for
  if (/^A\$[A-Za-z0-9]+$/.test(name)) return null;

  const elec = decodeElectrical(name);
  if (elec) {
    return {
      label: elec.label,
      discipline: 'electrical',
      evidence: elec.evidence,
      confidence: elec.confidence,
    };
  }

  for (const h of DISCIPLINE_HINTS) {
    if (!h.re.test(name)) continue;
    return {
      label: h.label ?? titleCase(name),
      discipline: h.discipline,
      // misspellings are common in real drawings ("Patition", "Tixt")
      evidence: `name matches ${h.discipline} convention`,
      confidence: h.label ? 0.8 : 0.6,
    };
  }

  return null;
}

function titleCase(s: string): string {
  return s
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/** domain decode expressed as a CadLabel, for the shared label map */
export function decodeAsLabel(raw: string): CadLabel | null {
  const d = decodeName(raw);
  if (!d) return null;
  return {
    label: d.label,
    discipline: d.discipline,
    evidence: d.evidence,
    confidence: d.confidence,
    userSet: false,
  };
}

/**
 * Confidence a rule must reach before it is allowed to STOP the model being
 * asked. Below this the rule has only tidied the raw name — "A-FURN-2" into
 * "A Furn 2" — which is not meaning, and letting it suppress the request would
 * make the output worse than having no rule at all. Such keys are still
 * offered as a provisional hint, but they go to the model too.
 */
export const RULE_AUTHORITY_THRESHOLD = 0.75;

/**
 * Split keys three ways: what rules can name with authority, what rules can
 * only guess at, and what they cannot touch. Only the first suppresses a
 * request; the other two are sent to the model.
 */
export function partitionKeys(keys: Iterable<string>): {
  /** confident enough to stand alone — no request needed */
  decoded: Map<string, CadLabel>;
  /** a weak guess; shown as a hint but still worth asking about */
  provisional: Map<string, CadLabel>;
  /** rules had nothing — this is what the model exists for */
  unknown: string[];
} {
  const decoded = new Map<string, CadLabel>();
  const provisional = new Map<string, CadLabel>();
  const unknown: string[] = [];
  for (const k of keys) {
    const l = decodeAsLabel(k);
    if (!l) {
      unknown.push(k);
    } else if ((l.confidence ?? 0) >= RULE_AUTHORITY_THRESHOLD) {
      decoded.set(k, l);
    } else {
      provisional.set(k, l);
      unknown.push(k);
    }
  }
  return { decoded, provisional, unknown };
}
